DELETE FROM Admin;
DELETE FROM Recordings;
DELETE FROM UserDataset;
DELETE FROM UserPhoto;
DELETE FROM UserData;
DELETE FROM UserScan;
DELETE FROM UserScanPhoto;

ALTER TABLE UserDataset AUTO_INCREMENT = 1;
ALTER TABLE UserPhoto AUTO_INCREMENT = 1;
ALTER TABLE UserData AUTO_INCREMENT = 1;
ALTER TABLE UserScan AUTO_INCREMENT = 1;
ALTER TABLE UserScanPhoto;
